# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2fa8593b8d2a84a03231c1e1baca83f3e03087d870e2c1b947e80e3db874a0565b8fedce5f635ecff9b438c58a2bee7c8ab36d47056c145ed6d54d5ef35ac29

test:
  secret_key_base: 51b88be74db085d25ce5f548e35391c4c733d14dcfadfee9da6e5a7455b72fa99faca2d3421f720aeb4eca55fd46867379c12ab3a980708c23ae2926480b74d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
